### PR TITLE
18 allow different input rasters for features

### PR DESCRIPTION
**Pull request by marcosbr**

### CODE REVIEW

**Comment by raplima** [comment]
- Program breaks in PredMap line [360](https://github.com/marcosbr/predictive-geology-maps/blob/8221f3749d1f70232e27d5358ab91d6a8dd35a52/predmap.py#L390) when there are no multi-band feature raster.
- Program breaks in functions line [232](https://github.com/marcosbr/predictive-geology-maps/blob/8221f3749d1f70232e27d5358ab91d6a8dd35a52/functions.py#L232) when user selects one multi-band feature raster and one single-band feature raster.

**Review by raplima — CHANGES_REQUESTED** [review]
Please check errors

**Comment by marcosbr** [comment]
> It seems the minimum number of feature rasters the program needs to not break in [functions line 232](https://github.com/marcosbr/predictive-geology-maps/blob/8221f3749d1f70232e27d5358ab91d6a8dd35a52/functions.py#L232) is 5 (1 multi-band, 4 single-band).

I will rearrange the code to separate the PCA option with this it will be easy to put an option to use or not the PCA function and fix the problem when the user does not select the multi-band feature raster.

**Comment by marcosbr** [comment]
> 

Fix

**Comment by marcosbr** [comment]
> > It seems the minimum number of feature rasters the program needs to not break in [functions line 232](https://github.com/marcosbr/predictive-geology-maps/blob/8221f3749d1f70232e27d5358ab91d6a8dd35a52/functions.py#L232) is 5 (1 multi-band, 4 single-band).
> 
> I will rearrange the code to separate the PCA option with this it will be easy to put an option to use or not the PCA function and fix the problem when the user does not select the multi-band feature raster.

Fixed

**Review by raplima — APPROVED** [review]
That seems to have fixed it!

**Pull request merged**
